// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgfDUvteRdZRcngsrk7MB0uXBDwupBig',
    appId: '1:30085220136:web:52fd6e6e305745d597321d',
    messagingSenderId: '30085220136',
    projectId: 'ltmb786',
    authDomain: 'ltmb786.firebaseapp.com',
    storageBucket: 'ltmb786.firebasestorage.app',
    measurementId: 'G-GYQZTDXH9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbqj_Y5cWHklsk0rUa4INU1qfWtDqICLk',
    appId: '1:30085220136:android:daca2f1581699da297321d',
    messagingSenderId: '30085220136',
    projectId: 'ltmb786',
    storageBucket: 'ltmb786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yJncDrlnRe3IZQxeQreVQa53sJdiqow',
    appId: '1:30085220136:ios:9e601afef8229a0397321d',
    messagingSenderId: '30085220136',
    projectId: 'ltmb786',
    storageBucket: 'ltmb786.firebasestorage.app',
    iosBundleId: 'com.example.baicuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2yJncDrlnRe3IZQxeQreVQa53sJdiqow',
    appId: '1:30085220136:ios:9e601afef8229a0397321d',
    messagingSenderId: '30085220136',
    projectId: 'ltmb786',
    storageBucket: 'ltmb786.firebasestorage.app',
    iosBundleId: 'com.example.baicuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqgfDUvteRdZRcngsrk7MB0uXBDwupBig',
    appId: '1:30085220136:web:c10ccdf1d33f0e9497321d',
    messagingSenderId: '30085220136',
    projectId: 'ltmb786',
    authDomain: 'ltmb786.firebaseapp.com',
    storageBucket: 'ltmb786.firebasestorage.app',
    measurementId: 'G-N8VSEEMVTX',
  );
}
